name: fruit_ai
description: A Flutter Web app to upload an image and get a description from a server.

publish_to: 'none' 

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  universal_html: ^2.2.4

  http: ^1.2.2

  # Für das Auswählen/Knipsen eines Bildes (auch Web-kompatibel)
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/ananas.jpg
    - assets/images/bananas.jpg

